name: Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: skala
        cache-environment: true
        cache-downloads: true
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install package in development mode
      run: |
        pip install -e . --no-deps
      shell: micromamba-shell {0}

    - name: Check environment consistency
      run: |
        pip check
      shell: micromamba-shell {0}

    - name: Run pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
      shell: micromamba-shell {0}

    - name: Run tests with coverage
      run: >-
        pytest
        -v
        --doctest-modules
        --cov=skala --cov-report=xml --cov-report=term-missing --cov-report=html
        --durations=50 --durations-min=1.0
        --pyargs skala
        tests/
      shell: micromamba-shell {0}
